# Generated by Django 3.1.7 on 2021-03-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('plate', models.CharField(max_length=8)),
                ('check_in', models.BooleanField(default=False)),
                ('check_out', models.BooleanField(default=False)),
                ('pay', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parkings',
                'ordering': ['id'],
            },
        ),
    ]
