# Generated by Django 3.1.7 on 2021-03-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='check_in',
            field=models.BooleanField(default=True),
        ),
    ]
