# Generated by Django 3.1.7 on 2021-03-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0002_auto_20210322_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='check_in',
        ),
        migrations.AddField(
            model_name='parking',
            name='minutes',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parking',
            name='check_out',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='parking',
            name='pay',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
