# Generated by Django 3.1.7 on 2021-03-22 23:45

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0004_auto_20210322_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='plate',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_plate', message='This format is not valid', regex=re.compile('^[a-zA-Z]{3}[-]{1}[a-zA-z]{4}$'))]),
        ),
    ]
