# Generated by Django 3.1.7 on 2021-03-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0006_auto_20210323_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='reservation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
